### ISSUE TITLE
Time based cover not working

### ISSUE THREAD

**Issue by vrublevskys** [Sese-Schneider/ha-cover-time-based#13]
Hi! I have defined MQTT buttons and they are works properly
```
  - switch:
      unique_id: markiza_switch_open
      name: "Markiza Open"
      icon: mdi:blinds-open 
      state_topic: "tele/tasmota_sonoff/RESULT" 
      availability_topic: "tele/tasmota_sonoff/LWT" 
      payload_off: "AA B0 35 05 08 12AC 05E6 02B2 0186 22B0 481A3A3B2B2A3B2A3A3B2A3B2B2B2A3B2A3A3B2A3A3B2B2B2A3B2A3B2A3B2B2B2A3B2A3B2A3B2A3B2A 55" 
      payload_on: "AA B0 35 05 08 12AC 05E6 02B2 0186 22B0 481A3A3B2B2A3B2A3A3B2A3B2B2B2A3B2A3A3B2A3A3B2B2B2A3B2A3B2A3B2B2B2A3B2A3B2A3B2A3B2A 55" 
      payload_available: "Online" 
      payload_not_available: "Offline" 
      retain: false 
      qos: 1 
      command_topic: "cmnd/tasmota_sonoff/rfraw" 
    
  - switch:
      unique_id: markiza_switch_close
      name: "Markiza Close"
      icon: mdi:blinds
      state_topic: "tele/tasmota_sonoff/RESULT" 
      availability_topic: "tele/tasmota_sonoff/LWT" 
      payload_off: "AA B0 35 05 08 12DE 05DC 02BC 017C 2292 481A3A3B2B2A3B2A3A3B2A3B2B2B2A3B2A3A3B2A3A3B2B2B2A3B2A3B2A3B2B2B2A3B2B2B2A3B2B2B2A 55" 
      payload_on: "AA B0 35 05 08 12DE 05DC 02BC 017C 2292 481A3A3B2B2A3B2A3A3B2A3B2B2B2A3B2A3A3B2A3A3B2B2B2A3B2A3B2A3B2B2B2A3B2B2B2A3B2B2B2A 55" 
      payload_available: "Online" 
      payload_not_available: "Offline" 
      retain: false 
      qos: 1 
      command_topic: "cmnd/tasmota_sonoff/rfraw" 
```
Then I use `cover_time_based` integration to implement a cover
```
cover:
  - platform: cover_time_based
    devices:
      markiza_time_based:
        name: terrasse shutter
        open_switch_entity_id: switch.markiza_open
        close_switch_entity_id: switch.markiza_close
        travelling_time_down: 23
        travelling_time_up: 25
```
Added this cover to a panel, and nothing happens when I click buttons or drag a slider. Just see slider progress animation, but phisical cover not responds. What I did wrong?
