### ISSUE TITLE
Add support for existing cover entities

### ISSUE THREAD

**Issue by TheYves** [Sese-Schneider/ha-cover-time-based#15]
Hi there

I've been using [cover-rf-time-based](https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based) because it allowed me to simply use an existing cover entity instead of using switches for the open/close/stop actions. Since this repository has been archived, I'm curious if it would make sense to add a new configuration option "cover_entity_id" to this project and then directly use the corresponding services/actions from the cover entity. As far as I can tell, besides the documentation and configuration, it's just [this part](https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based/blob/eb0f70ba045b431e77b72336b6f7236e7a6658a7/custom_components/cover_rf_time_based/cover.py#L437) that is currently missing.

Use case: I have a third party integration for all my covers in my house, which doesn't provide any state for the cover. So I already have 10 cover entities and all I had to do, is wrapping them with "cover-rf-time-based" and configure the corresponding travel times. Using this integration, I first need to create 30 switches (open/close/stop for 10 entities) in order to get it to work. Or am I missing something?

So if this would be a useful enhancement for this integration and someone would like to implement this, I would love to sponsor a beer/coffee or two. 😊 Otherwise, I have to do it myself, but I'm not very familiar with python, so I would prefer the first option. 😊

**Comment by Sese-Schneider** [comment]
Hey @TheYves 
This sounds like a usefull addition, I try to come up with a pre-release which implements this for you to try out in the next few days.

**Comment by ElGatitaux** [comment]
Hello,

I'm also very interested in this feature. 
Is it already functional?

thank you!

ElGatitaux

**Comment by Sese-Schneider** [comment]
Hi @ElGatitaux 
I've not yet had the capacity to work on this due to my dayjob - but this is high on my list of things TODO once I have some spare time.
The change is really not that complex, PRs are always welcome 😉

**Comment by TheYves** [comment]
Hey there! I just stumbled over this great project https://github.com/rstrouse/ESPSomfy-RTS which not only solves this issue for me, but I can also ditch the whole Somfy Cloud integration, which I was not happy about in the first place. So thank you anyway for your response and time. 🙏

**Comment by luckyzor** [comment]
> Hey there! I just stumbled over this great project https://github.com/rstrouse/ESPSomfy-RTS which not only solves this issue for me, but I can also ditch the whole Somfy Cloud integration, which I was not happy about in the first place. So thank you anyway for your response and time. 🙏

I've used ESPSomfy-RTS, but now I have RTS and IO shutters, as I'm using thaoma via local api, for me ESPSomfy is now useless for me.
@Sese-Schneider if you need testers, contact me. this is really something I need :)
thanks

**Comment by mediocaballero** [comment]
Another ex-user of rf-cover-time-based stumbling here... It'd be great to have that feature. Currently I'm using RFLink integration, which provides me a cover, but without percentage.

**Comment by TheYves** [comment]
> > Hey there! I just stumbled over this great project https://github.com/rstrouse/ESPSomfy-RTS which not only solves this issue for me, but I can also ditch the whole Somfy Cloud integration, which I was not happy about in the first place. So thank you anyway for your response and time. 🙏
> 
> I've used ESPSomfy-RTS, but now I have RTS and IO shutters, as I'm using thaoma via local api, ESPSomfy is now useless for me. @Sese-Schneider if you need testers, contact me. this is really something I need :) thanks

I also have two windows using IO which is why I still have to use the Somfy/Tahoma Connectivity Kit for these. But since the Connectivity Kit doesn't support local API and a device which does have local support isn't that cheap, I've decided to use ESPSomfy instead for all my shutters. I still hope I can replace the IO windows sometime. And by the way, the local API from Tahoma isn't that local anyway, because it still requires connectivity to the cloud for authorization from time to time. At least as far as I know.

Aaaand ESPSomfy has one huge bonus feature which the Tahoma devices lack: You can send a signal multiple times. For me that changed everything, because since the RTS protocol is unidirectional, the signal sometimes doesn't get to all of my shutters. Having ESPSomfy sending the same signal multiple times, it "ensures" that at least one signal gets through.

**Comment by viclive79** [comment]
Wasn't this capability already in the version that this was forked from? Wasn't sure if that would help get it included easier. I have not reviewed what the implimentation was. https://github.com/davidramosweb/home-assistant-custom-components-cover-time-based

**Comment by gbasile** [comment]
+1 on this being really nice!

**Comment by Ojoachim71** [comment]
+1 !

**Comment by Ojoachim71** [comment]
> Wasn't this capability already in the version that this was forked from? Wasn't sure if that would help get it included easier. I have not reviewed what the implimentation was. nagyrobi - https://github.com/nagyrobi/home-assistant-custom-components-cover-rf-time-based

Its about following the actual postition when triggering the entity externaly. This feature is lacking.

**Comment by Sese-Schneider** [comment]
Hey everyone!
I've published a pre-release `v2.3.0-beta.1` which is now available in the HACS. It contains support for using existing cover entities.

Please give it a try and test if it fits your needs.
Let me know if there are any issues!

**Comment by jujuforce** [comment]
Thanks a lot, I'll be trying it asap!

**Comment by gbasile** [comment]
For me it's not working :( 

I have commented the open/close/stop configurations and replaced them with the `cover_entity_id` as shown here

```
cover:
  - platform: cover_time_based
    devices:
      living_room_cover_position:
        name: Living Room Cover Position
        cover_entity_id: cover.living_room_blinders # This is a group of 2 covers
        # open_switch_entity_id: script.cover_living_room_open
        # close_switch_entity_id: script.cover_living_room_close
        # stop_switch_entity_id: script.cover_living_room_stop
        travelling_time_down: 24
        travelling_time_up: 24
      kids_room_cover_position:
        name: Kids Room Cover Position
        cover_entity_id: cover.rollerblind_0007 # This is a standard cover
        # open_switch_entity_id: script.cover_kids_room_open
        # close_switch_entity_id: script.cover_kids_room_close
        # stop_switch_entity_id: script.cover_kids_room_stop
```

When I try to operate the blinders I get the following error: 

`Failed to perform the action cover/stop_cover. 'bool' object is not iterable`
