### ISSUE TITLE
Send open and close command even if the state is open or closed

### ISSUE THREAD

**Issue by epmsmid** [Sese-Schneider/ha-cover-time-based#20]
When someone uses the original remote of my screen, Home Assistant is out of sync.
When Home Assistent "thinks" the screen is open, but it's actually closed, it's not possible to open the screen using Home Assistant.
When Home Assistent "thinks" the screen is closed, but it's actually open, it's not possible to close the screen using Home Assistant.

I did a quick hack to set the position to 100 if it is 0 and cover close is pressed. When the screen is fully closed Home Assistant is in sync again.
I did a quick hack to set the position to 0 if it is 100 and cover open is pressed. When the screen is fully opened Home Assistant is in sync again.

Is it possible to change the behaviour like I implemented?

**Comment by Sese-Schneider** [comment]
This is a duplicate to an existing issue, in the meanwhile you can try to hack your way around it also with the provided services:

```
action: cover_time_based.set_known_position
data:
  entity_id: cover.your_cover_time_based_cover
  position: 50
```
