### ISSUE TITLE
Optional options not optional

### ISSUE THREAD

**Issue by julianmueller** [Sese-Schneider/ha-cover-time-based#9]
The "optional" options like `tilting_time_down` and `tilting_time_up` are not so optional, as I they need to be set. Otherwise my entities will not be available.

```yaml
cover:
  - platform: cover_time_based
    devices:
      room_rolling_shutter:
        name: Room Rolling
        open_switch_entity_id: switch.wall_switch_right
        close_switch_entity_id: switch.wall_switch_left
        travelling_time_down: 23
        travelling_time_up: 25
        tilting_time_down: 0
        tilting_time_up: 0
```

I would much rather just not write them down, or set them to `null`. With the current version, all my shutters appear to have a tilting mechanism (which they dont have), which takes no time to actually tilt.

PS: Also the indentation in your README is not how HA uses it. Rather use two spaces instead of tabs.

But still: Thanks for the great plugin!
